default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: taskapp_development
  pool: 5
  timeout: 5000
  username: dev
  password: beaky
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: taskapp_test
  pool: 5
  timeout: 5000
  username: dev
  password: beaky
  host: localhost

production:
  adapter: postgresql
  database: to_do_list_pg
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  url: <%= ENV.fetch("DATABASE_URL") %>
